export const gameNavigation = [
  {
    href: '/game/character',
    label: 'Character',
    detail: 'Character profile and attributes',
    symbol: '◇',
    icon: 'profile',
  },
  {
    href: null,
    label: 'Arsenal',
    detail: 'Items — Coming Soon',
    symbol: '▣',
    icon: 'arsenal',
    disabled: true,
  },
  {
    href: '/game/nexus',
    label: 'Nexus',
    detail: 'Disciplines, Techniques, Attunement, Ascension, and Severed Power',
    symbol: '✦',
    icon: 'nexus',
  },
  {
    href: '/game/world',
    label: 'World Map',
    detail: 'Travel, explore, and find your place in the world',
    symbol: '✥',
    icon: 'world',
  },
  {
    href: '/game/battle',
    label: 'Battle Hall',
    detail: 'Practice fights and combat',
    symbol: '⚔',
    icon: 'battle',
  },
  {
    href: '/game/training',
    label: 'Passive Training',
    detail: 'Start a timed background training plan',
    symbol: '◷',
    icon: 'training',
  },
] as const
