import type { WorldPosition, WorldRegion, WorldRoad, WorldSector } from './types'
import { buildAuthoredSectorCrossing } from './sector-crossings'

export const GRID_WIDTH = 13
export const GRID_HEIGHT = 9
export const STEP_MS = 1100
export const WORLD_REGIONS: readonly WorldRegion[] = [
  {
    id: 'aureth-crown',
    name: 'Aureth Crown',
    summary: 'Golden fields, old roads and the heart of civilization.',
    sector: 'S14-08',
    longitude: -29,
    latitude: 6,
    art: 'aureth-crown',
    color: '#b9a967',
  },
  {
    id: 'verdant-expanse',
    name: 'Verdant Expanse',
    summary: 'Ancient woodland, river settlements and forgotten paths.',
    sector: 'S18-08',
    longitude: 14,
    latitude: 2,
    art: 'verdant-expanse',
    color: '#447c53',
  },
  {
    id: 'emberreach',
    name: 'Emberreach',
    summary: 'Basalt citadels beneath the glow of the volcanic frontier.',
    sector: 'S21-06',
    longitude: 50,
    latitude: 25,
    art: 'emberreach',
    color: '#b75434',
  },
  {
    id: 'frostmere',
    name: 'Frostmere',
    summary: 'Snowbound passes and warm lights beneath the mountain peaks.',
    sector: 'S17-04',
    longitude: 0,
    latitude: 55,
    art: 'frostmere',
    color: '#a3cbd6',
  },
  {
    id: 'glasswind-desert',
    name: 'Glasswind Desert',
    summary: 'Wind-sculpted dunes and the traces of a buried civilization.',
    sector: 'S13-11',
    longitude: -40,
    latitude: -26,
    art: 'glasswind-desert',
    color: '#d9b165',
  },
  {
    id: 'hollow-coast',
    name: 'Hollow Coast',
    summary: 'Tidal ruins, weathered harbours and a haunted shoreline.',
    sector: 'S18-12',
    longitude: 21,
    latitude: -42,
    art: 'hollow-coast',
    color: '#789aa4',
  },
  {
    id: 'starfall-highlands',
    name: 'Starfall Highlands',
    summary: 'Violet crags, high observatories and strange lights in the sky.',
    sector: 'S13-05',
    longitude: -43,
    latitude: 34,
    art: 'starfall-highlands',
    color: '#9380b4',
  },
  {
    id: 'umbral-march',
    name: 'Umbral March',
    summary: 'Dark forests and watchfires on the dangerous frontier.',
    sector: 'S22-10',
    longitude: 57,
    latitude: -18,
    art: 'umbral-march',
    color: '#53636b',
  },
]

// Painted sector maps share a road/bridge grammar; collision rows are explicit authored data.
// # = trees/building/wall, ~ = river/chasm, . = wilderness, = = road, s = protected settlement.
const ROWS = [
  '######.###~##',
  '#sss##..##~..',
  '#s#s##..##~..',
  '#sss##....~..',
  'sssss========',
  '#sss##....~..',
  '###s#.....~..',
  '###s#.....~..',
  '###s==.###~##',
].map((row) => row.trim())
const CROWN_HINTERLAND_ROWS = [
  '###..###..###',
  '##...##...###',
  '#....##....##',
  '.....##......',
  '=============',
  '......##.....',
  '##....##....#',
  '###...##...##',
  '###..####..##',
] as const
const CROWN_NORTHFIELDS_ROWS = [
  '###...=...###',
  '##....=....##',
  '#.....=.....#',
  '......=......',
  '=============',
  '......=......',
  '#.....=.....#',
  '##....=....##',
  '###...=...###',
] as const
const CROWN_UPLANDS_ROWS = [
  '#####...#####',
  '####....#####',
  '###...#######',
  '##....#######',
  '=====...#####',
  '####=...#####',
  '####=....####',
  '####=.....###',
  '####=...#####',
] as const
const CROWN_ROAD_ROWS = [
  '###...##~~###',
  '#..#..##~~###',
  '#.....##~~###',
  '.......#~~...',
  '=============',
  '.......#~~...',
  '#.....##~~###',
  '##...###~~###',
  '########~~###',
] as const
// Optional exit rows align each endpoint with its own painted path.
const LINKS: readonly [string, string, string, number, number?, number?][] = [
  ['aureth-crown', 'crown-road', 'Crown Road', STEP_MS],
  ['crown-road', 'verdant-expanse', 'Crown Road', STEP_MS],
  ['aureth-crown', 'southern-caravan-road', 'Southern Caravan Road', STEP_MS],
  ['southern-caravan-road', 'glasswind-desert', 'Southern Caravan Road', STEP_MS],
  ['aureth-crown', 'highland-road', 'Highland Road', STEP_MS],
  ['highland-road', 'starfall-highlands', 'Highland Road', STEP_MS],
  ['starfall-highlands', 'northern-pass', 'Northern Pass', STEP_MS],
  ['northern-pass', 'frostmere', 'Northern Pass', STEP_MS],
  ['verdant-expanse', 'ember-road', 'Ember Road', STEP_MS],
  ['ember-road', 'emberreach', 'Ember Road', STEP_MS],
  ['verdant-expanse', 'coastal-road', 'Coastal Road', STEP_MS, 4, 3],
  ['coastal-road', 'hollow-coast', 'Coastal Road', STEP_MS, 3, 4],
  ['emberreach', 'eastern-march-road', 'Eastern March Road', STEP_MS],
  ['eastern-march-road', 'umbral-march', 'Eastern March Road', STEP_MS],
  ['hollow-coast', 'old-coast-road', 'Old Coast Road', STEP_MS],
  ['old-coast-road', 'umbral-march', 'Old Coast Road', STEP_MS],
]
const legacyRoads: WorldRoad[] = LINKS.flatMap(([a, b, name, durationMs, fromY = 4, toY = 4]) => [
  { from: { sectorId: a, x: 12, y: fromY }, to: { sectorId: b, x: 0, y: toY }, name, durationMs },
  { from: { sectorId: b, x: 0, y: toY }, to: { sectorId: a, x: 12, y: fromY }, name, durationMs },
])
const crownHinterland = {
  id: 'crown-hinterland',
  coordinate: 'S15-08',
  rows: CROWN_HINTERLAND_ROWS,
} as const
const crownNorthfields = {
  id: 'crown-northfields',
  coordinate: 'S14-07',
  rows: CROWN_NORTHFIELDS_ROWS,
} as const
const crownUplands = {
  id: 'crown-uplands',
  coordinate: 'S15-07',
  rows: CROWN_UPLANDS_ROWS,
} as const
const authoredRoads: WorldRoad[] = [
  ...buildAuthoredSectorCrossing({
    from: { id: 'aureth-crown', coordinate: 'S14-08', rows: ROWS },
    to: crownHinterland,
    fromOffset: 4,
    toOffset: 4,
    name: 'Crown Hinterland',
    durationMs: STEP_MS,
  }),
  ...buildAuthoredSectorCrossing({
    from: crownHinterland,
    to: { id: 'crown-road', coordinate: 'S16-08', rows: CROWN_ROAD_ROWS },
    fromOffset: 4,
    toOffset: 4,
    name: 'Crown Hinterland',
    durationMs: STEP_MS,
  }),
  ...buildAuthoredSectorCrossing({
    from: { id: 'aureth-crown', coordinate: 'S14-08', rows: ROWS },
    to: crownNorthfields,
    fromOffset: 6,
    toOffset: 6,
    name: 'Crown North Road',
    durationMs: STEP_MS,
  }),
  ...buildAuthoredSectorCrossing({
    from: crownNorthfields,
    to: crownUplands,
    fromOffset: 4,
    toOffset: 4,
    name: 'Northfields Crossroad',
    durationMs: STEP_MS,
  }),
  ...buildAuthoredSectorCrossing({
    from: crownHinterland,
    to: crownUplands,
    fromOffset: 4,
    toOffset: 4,
    name: 'Crown Upland Track',
    durationMs: STEP_MS,
  }),
]
const roads: WorldRoad[] = [...legacyRoads, ...authoredRoads]
export const CHARTED_SECTORS: readonly WorldSector[] = [
  ...WORLD_REGIONS.map((region): WorldSector => ({
    id: region.id,
    name: region.name,
    coordinate: region.sector,
    regionId: region.id,
    art: `/media/art/world/${region.art}-v01.webp`,
    panorama: `/media/art/world/${region.art}-panorama-v01.webp`,
    east: 12,
    north: 28,
    rows: ROWS,
    charted: true,
    landmarks: [
      { id: `${region.id}-settlement`, name: 'Settlement', kind: 'settlement', x: 2, y: 4 },
      { id: `${region.id}-watch`, name: 'Watchtower', kind: 'watchtower', x: 12, y: 4 },
      ...(region.id === 'umbral-march'
        ? [
            {
              id: 'last-survey',
              name: 'Last reliable survey',
              kind: 'frontier' as const,
              x: 6,
              y: 0,
            },
          ]
        : []),
    ],
    roads: roads.filter((road) => road.from.sectorId === region.id),
  })),
  {
    id: 'crown-road',
    name: 'Crown Road',
    coordinate: 'S16-08',
    regionId: 'aureth-crown',
    art: '/media/art/world/crown-road-v01.webp',
    panorama: '/media/art/world/crown-road-panorama-v01.webp',
    stepMs: 4000,
    east: 0,
    north: 8,
    rows: CROWN_ROAD_ROWS,
    charted: true,
    landmarks: [],
    roads: roads.filter((road) => road.from.sectorId === 'crown-road'),
  },
  {
    id: 'crown-hinterland',
    name: 'Crown Hinterland',
    coordinate: 'S15-08',
    regionId: 'aureth-crown',
    art: null,
    east: 0,
    north: 8,
    rows: CROWN_HINTERLAND_ROWS,
    charted: true,
    landmarks: [],
    roads: roads.filter((road) => road.from.sectorId === 'crown-hinterland'),
  },
  {
    id: 'crown-northfields',
    name: 'Crown Northfields',
    coordinate: 'S14-07',
    regionId: 'aureth-crown',
    art: null,
    east: 0,
    north: 8,
    rows: CROWN_NORTHFIELDS_ROWS,
    charted: true,
    landmarks: [],
    roads: roads.filter((road) => road.from.sectorId === 'crown-northfields'),
  },
  {
    id: 'crown-uplands',
    name: 'Crown Uplands',
    coordinate: 'S15-07',
    regionId: 'aureth-crown',
    art: null,
    east: 0,
    north: 8,
    rows: CROWN_UPLANDS_ROWS,
    charted: true,
    landmarks: [],
    roads: roads.filter((road) => road.from.sectorId === 'crown-uplands'),
  },
  {
    id: 'coastal-road',
    name: 'Coastal Road',
    coordinate: 'S18-10',
    regionId: 'hollow-coast',
    art: '/media/art/world/coastal-road-v01.webp',
    panorama: '/media/art/world/coastal-road-panorama-v01.webp',
    stepMs: 4000,
    east: 0,
    north: 8,
    rows: [
      '#############',
      '#############',
      '####..##..###',
      '=============',
      '..#....##....',
      '~~~~~~~~~~~~~',
      '~~~~~~~~~~~~~',
      '~~~~~~~~~~~~~',
      '~~~~~~~~~~~~~',
    ],
    charted: true,
    landmarks: [],
    roads: roads.filter((road) => road.from.sectorId === 'coastal-road'),
  },
  {
    id: 'ember-road',
    name: 'Ember Road',
    coordinate: 'S20-07',
    regionId: 'emberreach',
    art: '/media/art/world/ember-road-v01.webp',
    panorama: '/media/art/world/ember-road-panorama-v02.webp',
    stepMs: 4000,
    east: 0,
    north: 8,
    rows: [
      '#############',
      '#############',
      '#############',
      '..###..###...',
      '=============',
      '..##....###..',
      '#############',
      '#############',
      '#############',
    ],
    charted: true,
    landmarks: [],
    roads: roads.filter((road) => road.from.sectorId === 'ember-road'),
  },
  {
    id: 'southern-caravan-road',
    name: 'Southern Caravan Road',
    coordinate: 'S14-10',
    regionId: 'glasswind-desert',
    art: '/media/art/world/southern-caravan-road-v01.webp',
    panorama: '/media/art/world/southern-caravan-road-panorama-v02.webp',
    stepMs: 4000,
    east: 0,
    north: 8,
    rows: [
      '#############',
      '#############',
      '##....###..##',
      '.............',
      '=============',
      '.............',
      '###..###...##',
      '#############',
      '#############',
    ],
    charted: true,
    landmarks: [],
    roads: roads.filter((road) => road.from.sectorId === 'southern-caravan-road'),
  },
  {
    id: 'highland-road',
    name: 'Highland Road',
    coordinate: 'S14-06',
    regionId: 'starfall-highlands',
    art: '/media/art/world/highland-road-v01.webp',
    panorama: '/media/art/world/highland-road-panorama-v01.webp',
    stepMs: 4000,
    east: 0,
    north: 8,
    rows: [
      '#############',
      '#############',
      '#############',
      '..###...##...',
      '=============',
      '...##...###..',
      '#############',
      '#############',
      '#############',
    ],
    charted: true,
    landmarks: [],
    roads: roads.filter((road) => road.from.sectorId === 'highland-road'),
  },
  {
    id: 'northern-pass',
    name: 'Northern Pass',
    coordinate: 'S15-04',
    regionId: 'frostmere',
    art: '/media/art/world/northern-pass-v01.webp',
    panorama: '/media/art/world/northern-pass-panorama-v01.webp',
    stepMs: 4000,
    east: 0,
    north: 8,
    rows: [
      '#############',
      '#############',
      '#############',
      '##..#...#..##',
      '=============',
      '##...#...####',
      '#############',
      '#############',
      '#############',
    ],
    charted: true,
    landmarks: [],
    roads: roads.filter((road) => road.from.sectorId === 'northern-pass'),
  },
  {
    id: 'eastern-march-road',
    name: 'Eastern March Road',
    coordinate: 'S22-08',
    regionId: 'umbral-march',
    art: '/media/art/world/eastern-march-road-v01.webp',
    panorama: '/media/art/world/eastern-march-road-panorama-v01.webp',
    stepMs: 4000,
    east: 0,
    north: 8,
    rows: [
      '#############',
      '#############',
      '#############',
      '#############',
      '=============',
      '#############',
      '#############',
      '#############',
      '#############',
    ],
    charted: true,
    landmarks: [],
    roads: roads.filter((road) => road.from.sectorId === 'eastern-march-road'),
  },
  {
    id: 'old-coast-road',
    name: 'Old Coast Road',
    coordinate: 'S20-11',
    regionId: 'umbral-march',
    art: '/media/art/world/old-coast-road-v01.webp',
    panorama: '/media/art/world/old-coast-road-panorama-v01.webp',
    stepMs: 4000,
    east: 0,
    north: 8,
    rows: [
      '#############',
      '#############',
      '#############',
      '#############',
      '=============',
      '#############',
      '#############',
      '#############',
      '#############',
    ],
    charted: true,
    landmarks: [],
    roads: roads.filter((road) => road.from.sectorId === 'old-coast-road'),
  },
]
export const START_POSITION: WorldPosition = { sectorId: 'verdant-expanse', x: 5, y: 4 }
export const FRONTIER_APPROACH: WorldPosition = { sectorId: 'umbral-march', x: 6, y: 0 }
export function worldRegion(id: string) {
  return WORLD_REGIONS.find((region) => region.id === id)
}
