import type { CombatEffectDefinition, CombatTargetSpec, CombatUseRequirement } from './actions'
import type { MatureSkillDefinition } from './mature-skills'
import type { EssenceDefinition } from './essence'
import { CLEANSE_STATUS_IDS } from './status-content'

const self: CombatTargetSpec = {
  kind: 'self',
  teamPolicy: 'self',
  shape: { kind: 'single' },
  minimumRange: 0,
  maximumRange: 0,
  requiresLineOfSight: false,
  maximumElevationDifference: null,
  friendlyFire: 'allies-only',
}
const melee: CombatTargetSpec = {
  kind: 'unit',
  teamPolicy: 'enemy',
  shape: { kind: 'single' },
  minimumRange: 1,
  maximumRange: 1,
  requiresLineOfSight: false,
  maximumElevationDifference: 1,
  friendlyFire: 'enemies-only',
}
const ranged: CombatTargetSpec = {
  ...melee,
  maximumRange: 4,
  requiresLineOfSight: true,
  maximumElevationDifference: 2,
}
const ally: CombatTargetSpec = {
  ...ranged,
  teamPolicy: 'ally',
  minimumRange: 0,
  friendlyFire: 'allies-only',
  maximumRange: 3,
}
const area = (target: CombatTargetSpec, radius = 1): CombatTargetSpec => ({
  ...target,
  shape: { kind: 'circle', radius },
})
const line = (target: CombatTargetSpec, length = 3): CombatTargetSpec => ({
  ...target,
  maximumRange: length,
  shape: { kind: 'line', length },
})
const damage = (
  amount: number,
  recipient: CombatEffectDefinition['recipient'] = 'primary-unit',
): CombatEffectDefinition => ({ type: 'damage', amount, recipient })
const heal = (
  amount: number,
  recipient: CombatEffectDefinition['recipient'] = 'actor',
): CombatEffectDefinition => ({ type: 'healing', amount, recipient })
const effect = (
  statusId: string,
  recipient: CombatEffectDefinition['recipient'] = 'primary-unit',
): CombatEffectDefinition => ({ type: 'apply-status', statusId, recipient, stacks: 1 })
const mp = (
  delta: number,
  recipient: CombatEffectDefinition['recipient'] = 'actor',
): CombatEffectDefinition => ({ type: 'resource-change', resource: 'mp', delta, recipient })
const cleanse = (
  recipient: CombatEffectDefinition['recipient'] = 'actor',
): CombatEffectDefinition => ({ type: 'remove-status', recipient, statusIds: CLEANSE_STATUS_IDS })
const targetStatus = (statusId: string): CombatUseRequirement[] => [
  { kind: 'target-status-present', statusId },
]
const actorStatus = (statusId: string): CombatUseRequirement[] => [
  { kind: 'actor-status-present', statusId },
]
const lowHp: CombatUseRequirement[] = [{ kind: 'actor-hp-at-most', basisPoints: 5000 }]
function skill(
  discipline: string,
  key: string,
  apCost: number,
  target: CombatTargetSpec,
  effects: readonly CombatEffectDefinition[],
  tags: readonly string[],
  requirements: readonly CombatUseRequirement[] = [],
): MatureSkillDefinition {
  const id = `${discipline}.${key}`
  return {
    id,
    sourceDisciplineId: discipline,
    contentVersion: 1,
    enabled: true,
    nameRef: `skill.${id}.name`,
    descriptionRef: `skill.${id}.description`,
    unlockRequirement: { kind: 'discipline-mastery', minimumStage: 1 },
    apCost,
    mpCost: tags.includes('mystic') ? Math.max(2, Math.floor(apCost / 15)) : 0,
    target,
    effects,
    requirements,
    tags: [
      'discipline',
      discipline,
      ...tags,
      tags.includes('attack')
        ? 'cockpit:attack'
        : tags.includes('heal')
          ? 'cockpit:recovery'
          : 'cockpit:defense',
    ],
    cooldown: { key: id, ownerTurns: 2 },
    ai: { enabled: true, baseUtility: tags.includes('attack') ? 66 : 48, purposeTags: tags },
    overrides: {},
    media: {
      iconKey: `skill.${id}.icon`,
      audioCueKey: `skill.${id}.audio`,
      vfxKey: `skill.${id}.vfx`,
    },
    authoring: {
      schemaVersion: 1,
      status: 'representative',
      validationTags: ['p4', discipline, 'shared-combat-authority'],
    },
  }
}

const authoredSkills: readonly MatureSkillDefinition[] = [
  // Chronist changes next-round ordering, never duplicates turns or refunds past commands.
  skill('chronist', 'temporal-bolt', 35, ranged, [damage(10)], ['attack', 'mystic', 'ranged']),
  skill('chronist', 'haste', 30, ally, [effect('hastened')], ['support', 'tempo', 'mystic']),
  skill(
    'chronist',
    'slow',
    35,
    ranged,
    [damage(4), effect('slow')],
    ['attack', 'mystic', 'control'],
  ),
  skill('chronist', 'delay', 35, ranged, [effect('delayed')], ['control', 'tempo', 'mystic']),
  skill(
    'chronist',
    'rewind-step',
    40,
    self,
    [{ type: 'return-to-turn-start', recipient: 'actor' }],
    ['movement', 'mystic'],
  ),
  skill(
    'chronist',
    'time-lock',
    50,
    ranged,
    [effect('root'), effect('delayed')],
    ['control', 'tempo', 'mystic'],
  ),
  skill(
    'chronist',
    'temporal-ward',
    40,
    self,
    [effect('guarded', 'actor'), effect('hastened', 'actor')],
    ['defense', 'tempo', 'mystic'],
  ),
  skill(
    'chronist',
    'stolen-moment',
    45,
    ranged,
    [damage(17), mp(3)],
    ['attack', 'mystic', 'finisher'],
    targetStatus('delayed'),
  ),

  // Bastion trades personal pressure for protection and target-sensitive threat control.
  skill(
    'bastion',
    'shield-bash',
    35,
    melee,
    [damage(6), effect('slow')],
    ['attack', 'melee', 'control', 'setup'],
  ),
  skill('bastion', 'cover', 30, ally, [effect('guarded')], ['defense', 'support', 'setup']),
  skill('bastion', 'challenge', 25, ranged, [effect('challenged')], ['control', 'setup']),
  skill(
    'bastion',
    'fortress',
    30,
    self,
    [effect('fortified', 'actor')],
    ['defense', 'tradeoff', 'setup'],
  ),
  skill(
    'bastion',
    'hold-fast',
    40,
    self,
    [heal(10), effect('guarded', 'actor')],
    ['heal', 'defense'],
    lowHp,
  ),
  skill(
    'bastion',
    'shield-line',
    45,
    line(melee),
    [damage(7, 'affected-units')],
    ['attack', 'melee', 'line'],
  ),
  skill(
    'bastion',
    'stalwart-strike',
    40,
    melee,
    [damage(14)],
    ['attack', 'melee', 'payoff'],
    actorStatus('guarded'),
  ),
  skill(
    'bastion',
    'steady-footing',
    30,
    self,
    [
      { type: 'remove-status', recipient: 'actor', statusIds: ['slow', 'root'] },
      effect('guarded', 'actor'),
    ],
    ['cleanse', 'defense'],
  ),
  // Ravager's strongest output is scarce and carries a linked incoming-damage penalty.
  skill('ravager', 'frenzy', 30, self, [effect('reckless', 'actor')], ['tradeoff', 'setup']),
  skill(
    'ravager',
    'gash',
    35,
    melee,
    [damage(6), effect('bleed')],
    ['attack', 'melee', 'bleed', 'setup'],
  ),
  skill(
    'ravager',
    'cleaving-blow',
    45,
    area(melee),
    [damage(8, 'affected-units')],
    ['attack', 'melee', 'area'],
  ),
  skill('ravager', 'blood-rush', 35, melee, [heal(12)], ['heal', 'payoff'], targetStatus('bleed')),
  skill(
    'ravager',
    'war-roar',
    35,
    area(melee),
    [effect('exposed', 'affected-units')],
    ['control', 'expose', 'setup'],
  ),
  skill(
    'ravager',
    'desperate-execution',
    45,
    melee,
    [damage(20)],
    ['attack', 'melee', 'finisher'],
    lowHp,
  ),
  skill('ravager', 'blood-siphon', 45, melee, [damage(7), heal(5)], ['attack', 'melee', 'heal']),
  skill(
    'ravager',
    'open-wound',
    40,
    melee,
    [damage(15)],
    ['attack', 'melee', 'payoff'],
    targetStatus('bleed'),
  ),
  // Edgedancer exploits facing and alternates precise setup with conditional finishers.
  skill(
    'edgedancer',
    'lunge',
    40,
    { ...melee, maximumRange: 2 },
    [damage(11)],
    ['attack', 'melee', 'reach'],
  ),
  skill(
    'edgedancer',
    'riposte',
    35,
    melee,
    [damage(14)],
    ['attack', 'melee', 'payoff'],
    actorStatus('guarded'),
  ),
  skill(
    'edgedancer',
    'hamstring',
    35,
    melee,
    [damage(5), effect('slow')],
    ['attack', 'melee', 'control', 'setup'],
  ),
  skill(
    'edgedancer',
    'flourish',
    35,
    melee,
    [damage(6), effect('exposed')],
    ['attack', 'melee', 'expose', 'setup'],
  ),
  skill('edgedancer', 'poised-guard', 25, self, [effect('guarded', 'actor')], ['defense', 'setup']),
  skill(
    'edgedancer',
    'flanking-cut',
    45,
    melee,
    [
      {
        type: 'damage',
        recipient: 'primary-unit',
        amount: 9,
        facingModifiersBasisPoints: { front: 10000, side: 14000, rear: 17000 },
      },
    ],
    ['attack', 'melee', 'facing'],
  ),
  skill(
    'edgedancer',
    'severing-cut',
    40,
    melee,
    [damage(7), effect('bleed')],
    ['attack', 'melee', 'bleed'],
  ),
  skill(
    'edgedancer',
    'finishing-thrust',
    45,
    melee,
    [damage(18)],
    ['attack', 'melee', 'payoff'],
    targetStatus('exposed'),
  ),
  // Wildwarden combines range control, attrition and a mark limited to its own source.
  skill('wildwarden', 'snare', 40, ranged, [effect('root')], ['control', 'setup']),
  skill('wildwarden', 'hunters-mark', 25, ranged, [effect('marked')], ['mark', 'setup']),
  skill(
    'wildwarden',
    'venom-shot',
    40,
    { ...ranged, minimumRange: 2, maximumRange: 5 },
    [damage(5), effect('poison')],
    ['attack', 'ranged', 'poison', 'setup'],
  ),
  skill('wildwarden', 'field-remedy', 35, self, [heal(5), cleanse()], ['heal', 'cleanse']),
  skill(
    'wildwarden',
    'thorn-line',
    45,
    line(ranged),
    [damage(6, 'affected-units'), effect('slow', 'affected-units')],
    ['attack', 'ranged', 'line', 'control'],
  ),
  skill(
    'wildwarden',
    'pursuit-shot',
    40,
    ranged,
    [damage(14)],
    ['attack', 'ranged', 'payoff'],
    targetStatus('slow'),
  ),
  skill(
    'wildwarden',
    'renewing-herbs',
    30,
    ally,
    [effect('regeneration')],
    ['heal', 'support', 'setup'],
  ),
  skill(
    'wildwarden',
    'close-quarry',
    35,
    melee,
    [damage(10), mp(3)],
    ['attack', 'melee', 'recovery'],
  ),
  // Runeblade alternates melee and mystic attacks with MP pressure and cleansing.
  skill(
    'runeblade',
    'arc-edge',
    40,
    line(melee, 2),
    [damage(10, 'affected-units')],
    ['attack', 'mystic', 'line'],
  ),
  skill(
    'runeblade',
    'rune-guard',
    30,
    self,
    [effect('guarded', 'actor'), mp(3)],
    ['defense', 'setup'],
  ),
  skill(
    'runeblade',
    'siphon-slash',
    40,
    melee,
    [damage(6), mp(-4, 'primary-unit'), mp(4)],
    ['attack', 'melee', 'drain'],
  ),
  skill(
    'runeblade',
    'sigil-brand',
    35,
    melee,
    [damage(5), effect('exposed')],
    ['attack', 'melee', 'expose', 'setup'],
  ),
  skill(
    'runeblade',
    'rune-burst',
    45,
    ranged,
    [damage(16)],
    ['attack', 'mystic', 'payoff'],
    targetStatus('exposed'),
  ),
  skill('runeblade', 'unbinding-rune', 35, self, [cleanse()], ['cleanse', 'support']),
  skill('runeblade', 'aether-cut', 35, melee, [damage(12)], ['attack', 'mystic', 'melee']),
  skill(
    'runeblade',
    'rune-mending',
    40,
    self,
    [heal(10)],
    ['heal', 'payoff'],
    actorStatus('guarded'),
  ),
  // Dawnshield lends defense and removes harmful statuses, sacrificing ranged pressure.
  skill(
    'dawnshield',
    'radiant-strike',
    35,
    melee,
    [damage(9), effect('guarded', 'actor')],
    ['attack', 'mystic', 'melee', 'setup'],
  ),
  skill(
    'dawnshield',
    'sacred-guard',
    35,
    ally,
    [effect('guarded'), heal(4, 'primary-unit')],
    ['defense', 'heal', 'support', 'setup'],
  ),
  skill('dawnshield', 'purge', 30, ally, [cleanse('primary-unit')], ['cleanse', 'support']),
  skill(
    'dawnshield',
    'consecrated-light',
    45,
    area(ally),
    [heal(8, 'affected-units')],
    ['heal', 'area', 'support'],
  ),
  skill(
    'dawnshield',
    'aegis',
    45,
    area(ally),
    [effect('guarded', 'affected-units')],
    ['defense', 'area', 'setup'],
  ),
  skill(
    'dawnshield',
    'renewal',
    35,
    self,
    [effect('regeneration', 'actor'), cleanse()],
    ['heal', 'cleanse', 'setup'],
  ),
  skill(
    'dawnshield',
    'judgment',
    45,
    melee,
    [damage(16)],
    ['attack', 'mystic', 'payoff'],
    actorStatus('guarded'),
  ),
  skill('dawnshield', 'last-light', 40, self, [heal(16)], ['heal', 'recovery'], lowHp),
  // Cinderweaver establishes Burn, then converts it into area pressure or a payoff.
  skill(
    'cinderweaver',
    'cinder-bolt',
    35,
    ranged,
    [damage(6), effect('burn')],
    ['attack', 'mystic', 'burn', 'setup'],
  ),
  skill(
    'cinderweaver',
    'flame-burst',
    45,
    area(ranged),
    [damage(8, 'affected-units')],
    ['attack', 'mystic', 'area'],
  ),
  skill(
    'cinderweaver',
    'ember-line',
    45,
    line(ranged),
    [damage(5, 'affected-units'), effect('burn', 'affected-units')],
    ['attack', 'mystic', 'line', 'burn', 'setup'],
  ),
  skill(
    'cinderweaver',
    'scorch',
    40,
    ranged,
    [damage(16)],
    ['attack', 'mystic', 'payoff'],
    targetStatus('burn'),
  ),
  skill('cinderweaver', 'ash-ward', 30, self, [effect('warded', 'actor')], ['defense', 'setup']),
  skill(
    'cinderweaver',
    'flashfire',
    35,
    melee,
    [damage(11), effect('exposed')],
    ['attack', 'mystic', 'expose'],
  ),
  skill('cinderweaver', 'banked-embers', 35, self, [mp(8), heal(4)], ['heal', 'recovery']),
  skill(
    'cinderweaver',
    'blistering-heat',
    40,
    ranged,
    [effect('burn'), effect('slow')],
    ['control', 'burn', 'setup'],
  ),
  // Frostweaver controls movement and rewards allies for holding targets in place.
  skill(
    'frostweaver',
    'ice-lance',
    35,
    ranged,
    [damage(7), effect('slow')],
    ['attack', 'mystic', 'control', 'setup'],
  ),
  skill('frostweaver', 'frost-guard', 30, self, [effect('guarded', 'actor')], ['defense', 'setup']),
  skill(
    'frostweaver',
    'chilling-mist',
    45,
    area(ranged),
    [effect('slow', 'affected-units')],
    ['control', 'area', 'setup'],
  ),
  skill('frostweaver', 'crystal-prison', 45, ranged, [effect('root')], ['control', 'setup']),
  skill(
    'frostweaver',
    'shatter',
    40,
    ranged,
    [damage(16)],
    ['attack', 'mystic', 'payoff'],
    targetStatus('root'),
  ),
  skill(
    'frostweaver',
    'ice-line',
    45,
    line(ranged),
    [damage(9, 'affected-units')],
    ['attack', 'mystic', 'line'],
  ),
  skill(
    'frostweaver',
    'thaw',
    30,
    ally,
    [
      { type: 'remove-status', recipient: 'primary-unit', statusIds: ['root', 'slow', 'burn'] },
      heal(4, 'primary-unit'),
    ],
    ['cleanse', 'heal', 'support'],
  ),
  skill(
    'frostweaver',
    'brittle-ice',
    35,
    ranged,
    [damage(5), effect('exposed')],
    ['attack', 'mystic', 'expose', 'setup'],
  ),
  // Stormsinger controls firing lanes and drains MP while vulnerable at close range.
  skill('stormsinger', 'arc-spark', 35, ranged, [damage(10)], ['attack', 'mystic', 'ranged']),
  skill(
    'stormsinger',
    'lightning-line',
    45,
    line({ ...ranged, minimumRange: 2 }, 4),
    [damage(9, 'affected-units')],
    ['attack', 'mystic', 'line'],
  ),
  skill(
    'stormsinger',
    'static-burst',
    45,
    area(ranged),
    [damage(4, 'affected-units'), effect('slow', 'affected-units')],
    ['attack', 'mystic', 'control', 'setup'],
  ),
  skill(
    'stormsinger',
    'thunderclap',
    40,
    melee,
    [damage(8), effect('exposed')],
    ['attack', 'mystic', 'expose', 'setup'],
  ),
  skill(
    'stormsinger',
    'grounding',
    30,
    self,
    [{ type: 'remove-status', recipient: 'actor', statusIds: ['slow', 'root', 'marked'] }, mp(3)],
    ['cleanse', 'recovery'],
  ),
  skill(
    'stormsinger',
    'static-drain',
    40,
    ranged,
    [damage(4), mp(-6, 'primary-unit')],
    ['attack', 'mystic', 'drain'],
  ),
  skill(
    'stormsinger',
    'conductive-bolt',
    45,
    ranged,
    [damage(16)],
    ['attack', 'mystic', 'payoff'],
    targetStatus('slow'),
  ),
  skill('stormsinger', 'storm-breath', 35, self, [mp(10)], ['recovery', 'setup']),
  // Tidecaller combines support and control, with no persistent-zone claims.
  skill('tidecaller', 'water-lance', 35, ranged, [damage(10)], ['attack', 'mystic', 'ranged']),
  skill('tidecaller', 'mist-veil', 30, ally, [effect('guarded')], ['defense', 'support', 'setup']),
  skill(
    'tidecaller',
    'undertow',
    40,
    ranged,
    [damage(5), effect('slow')],
    ['attack', 'mystic', 'control', 'setup'],
  ),
  skill(
    'tidecaller',
    'cleansing-rain',
    50,
    area(ally),
    [cleanse('affected-units'), heal(3, 'affected-units')],
    ['cleanse', 'heal', 'area', 'support'],
  ),
  skill(
    'tidecaller',
    'flood-line',
    45,
    line(ranged),
    [damage(7, 'affected-units'), effect('slow', 'affected-units')],
    ['attack', 'mystic', 'line', 'control'],
  ),
  skill(
    'tidecaller',
    'springwater',
    35,
    ally,
    [effect('regeneration')],
    ['heal', 'support', 'setup'],
  ),
  skill('tidecaller', 'still-water', 35, self, [heal(6), mp(5)], ['heal', 'recovery']),
  skill(
    'tidecaller',
    'crushing-wave',
    45,
    ranged,
    [damage(15)],
    ['attack', 'mystic', 'payoff'],
    targetStatus('slow'),
  ),
]

export const ADVANCED_DISCIPLINE_SKILLS: readonly MatureSkillDefinition[] = authoredSkills.map(
  (definition, index) => ({
    ...definition,
    unlockRequirement: {
      kind: 'discipline-mastery',
      minimumStage: index % 8 < 4 ? 1 : index % 8 < 6 ? 2 : 3,
    },
  }),
)

function essence(
  discipline: string,
  key: string,
  name: string,
  description: string,
  ap: number,
  target: CombatTargetSpec,
  effects: readonly CombatEffectDefinition[],
  tags: readonly string[],
): EssenceDefinition {
  const base = skill(discipline, key, ap, target, effects, tags)
  const id = `essence.${discipline}.${key}`
  return {
    essenceId: id,
    contentVersion: 1,
    enabled: true,
    sourceDisciplineId: discipline,
    name,
    description,
    skill: {
      ...base,
      id,
      nameRef: `${id}.name`,
      descriptionRef: `${id}.description`,
      tags: ['essence', ...base.tags.filter((tag) => tag !== 'discipline')],
      cooldown: { key: id, ownerTurns: 4 },
      overrides: { pvp: { apCost: Math.min(100, ap + 5) } },
      media: { iconKey: `${id}.icon`, audioCueKey: `${id}.audio`, vfxKey: `${id}.vfx` },
    },
    authoring: base.authoring,
  }
}
export const ADVANCED_DISCIPLINE_ESSENCES: readonly EssenceDefinition[] = [
  essence(
    'chronist',
    'borrowed-hour',
    'Borrowed Hour',
    'Restore an ally and prepare +40 Initiative for the next round. No extra turn, AP or battle reset.',
    60,
    ally,
    [heal(10, 'primary-unit'), effect('borrowed-hour')],
    ['heal', 'support', 'tempo', 'mystic'],
  ),
  essence(
    'bastion',
    'last-bastion',
    'Last Bastion',
    'Recover and fortify yourself, sacrificing damage dealt for strong protection.',
    60,
    self,
    [heal(16), effect('fortified', 'actor')],
    ['heal', 'defense', 'tradeoff'],
  ),
  essence(
    'ravager',
    'red-tempest',
    'Red Tempest',
    'Strike nearby enemies and open bleeding wounds. Spacing limits the sweep.',
    65,
    area(melee),
    [damage(13, 'affected-units'), effect('bleed', 'affected-units')],
    ['attack', 'melee', 'area', 'bleed'],
  ),
  essence(
    'edgedancer',
    'sevenfold-cut',
    'Sevenfold Cut',
    'Seven small cuts reward an opening; defenses resolve separately for every hit.',
    65,
    melee,
    Array.from({ length: 7 }, () => damage(3)),
    ['attack', 'melee', 'finisher'],
  ),
  essence(
    'wildwarden',
    'apex-hunt',
    'Apex Hunt',
    'Strike and root your quarry at range, preparing an approach or retreat.',
    60,
    { ...ranged, minimumRange: 2, maximumRange: 5 },
    [damage(16), effect('root')],
    ['attack', 'ranged', 'control'],
  ),
  essence(
    'runeblade',
    'runic-overdrive',
    'Runic Overdrive',
    'Cut a mystic line through enemies and restore your MP.',
    60,
    line(melee, 3),
    [damage(16, 'affected-units'), mp(6)],
    ['attack', 'mystic', 'line'],
  ),
  essence(
    'dawnshield',
    'dawns-oath',
    'Dawn’s Oath',
    'Cleanse, heal and guard a nearby ally. Separation can deny the rescue.',
    60,
    ally,
    [cleanse('primary-unit'), heal(16, 'primary-unit'), effect('guarded')],
    ['heal', 'defense', 'support'],
  ),
  essence(
    'cinderweaver',
    'phoenix-wake',
    'Phoenix Wake',
    'Burn enemies in an immediate fiery burst. Spread out to limit its impact.',
    65,
    area(ranged, 2),
    [damage(10, 'affected-units'), effect('burn', 'affected-units')],
    ['attack', 'mystic', 'area', 'burn'],
  ),
  essence(
    'frostweaver',
    'absolute-winter',
    'Absolute Winter',
    'Freeze enemies in a small area, denying movement while leaving their Skills available.',
    65,
    area(ranged),
    [damage(7, 'affected-units'), effect('root', 'affected-units')],
    ['attack', 'mystic', 'area', 'control'],
  ),
  essence(
    'stormsinger',
    'skybreak',
    'Skybreak',
    'Send a powerful lightning strike down a long line; break sight or leave the lane.',
    65,
    line(ranged, 5),
    [damage(18, 'affected-units')],
    ['attack', 'mystic', 'line'],
  ),
  essence(
    'tidecaller',
    'tidal-crown',
    'Tidal Crown',
    'Cleanse and restore allies in a small area, then regenerate their HP.',
    65,
    area(ally),
    [
      cleanse('affected-units'),
      heal(10, 'affected-units'),
      effect('regeneration', 'affected-units'),
    ],
    ['heal', 'area', 'support'],
  ),
]
