const selfTarget = {
  kind: 'self',
  teamPolicy: 'self',
  shape: { kind: 'single' },
  minimumRange: 0,
  maximumRange: 0,
  requiresLineOfSight: false,
  maximumElevationDifference: null,
  friendlyFire: 'allies-only',
} as const

const mysticEnemyTarget = {
  kind: 'unit',
  teamPolicy: 'enemy',
  shape: { kind: 'single' },
  minimumRange: 1,
  maximumRange: 4,
  requiresLineOfSight: true,
  maximumElevationDifference: 2,
  friendlyFire: 'enemies-only',
} as const

const farEnemyTarget = {
  kind: 'unit',
  teamPolicy: 'enemy',
  shape: { kind: 'single' },
  minimumRange: 2,
  maximumRange: 5,
  requiresLineOfSight: true,
  maximumElevationDifference: 3,
  friendlyFire: 'enemies-only',
} as const

const meleeEnemyTarget = {
  kind: 'unit',
  teamPolicy: 'enemy',
  shape: { kind: 'single' },
  minimumRange: 1,
  maximumRange: 1,
  requiresLineOfSight: false,
  maximumElevationDifference: 1,
  friendlyFire: 'enemies-only',
} as const

function media(skillId: string) {
  return {
    iconKey: `skill.${skillId}.icon`,
    audioCueKey: `skill.${skillId}.audio`,
    vfxKey: `skill.${skillId}.vfx`,
  }
}

function authoring(disciplineId: string, origin: 'master-plan-concept' | 'class-expansion') {
  return {
    schemaVersion: 1 as const,
    status: 'representative' as const,
    validationTags: ['p3.8', 'foundation-trio', disciplineId, origin],
  }
}

export const FOUNDATION_TRIO_DISCIPLINE_SKILLS = [
  {
    id: 'aetherist.arc-bolt',
    contentVersion: 1,
    enabled: true,
    nameRef: 'skill.aetherist.arc-bolt.name',
    descriptionRef: 'skill.aetherist.arc-bolt.description',
    sourceDisciplineId: 'aetherist',
    unlockRequirement: { kind: 'discipline-mastery', minimumStage: 1 },
    apCost: 35,
    target: mysticEnemyTarget,
    requirements: [],
    effects: [{ type: 'damage', recipient: 'primary-unit', amount: 9 }],
    tags: ['discipline', 'aetherist', 'attack', 'mystic', 'ranged', 'cockpit:attack'],
    cooldown: { key: 'aetherist.arc-bolt', ownerTurns: 2 },
    ai: { enabled: true, baseUtility: 68, purposeTags: ['damage', 'pressure'] },
    overrides: {},
    media: media('aetherist.arc-bolt'),
    authoring: authoring('aetherist', 'master-plan-concept'),
  },
  {
    id: 'aetherist.mana-burst',
    contentVersion: 1,
    enabled: true,
    nameRef: 'skill.aetherist.mana-burst.name',
    descriptionRef: 'skill.aetherist.mana-burst.description',
    sourceDisciplineId: 'aetherist',
    unlockRequirement: { kind: 'discipline-mastery', minimumStage: 1 },
    apCost: 50,
    target: { ...mysticEnemyTarget, maximumRange: 3, shape: { kind: 'circle', radius: 1 } },
    requirements: [],
    effects: [{ type: 'damage', recipient: 'affected-units', amount: 7 }],
    tags: ['discipline', 'aetherist', 'attack', 'mystic', 'ranged', 'area', 'cockpit:attack'],
    cooldown: { key: 'aetherist.mana-burst', ownerTurns: 3 },
    ai: { enabled: true, baseUtility: 71, purposeTags: ['damage', 'area', 'pressure'] },
    overrides: {},
    media: media('aetherist.mana-burst'),
    authoring: authoring('aetherist', 'master-plan-concept'),
  },
  {
    id: 'aetherist.ward-pierce',
    contentVersion: 1,
    enabled: true,
    nameRef: 'skill.aetherist.ward-pierce.name',
    descriptionRef: 'skill.aetherist.ward-pierce.description',
    sourceDisciplineId: 'aetherist',
    unlockRequirement: { kind: 'discipline-mastery', minimumStage: 1 },
    apCost: 45,
    target: mysticEnemyTarget,
    requirements: [],
    effects: [
      { type: 'damage', recipient: 'primary-unit', amount: 8 },
      { type: 'apply-status', recipient: 'primary-unit', statusId: 'exposed', stacks: 1 },
    ],
    tags: ['discipline', 'aetherist', 'attack', 'mystic', 'ranged', 'expose', 'cockpit:attack'],
    cooldown: { key: 'aetherist.ward-pierce', ownerTurns: 3 },
    ai: { enabled: true, baseUtility: 73, purposeTags: ['damage', 'debuff', 'setup'] },
    overrides: {},
    media: media('aetherist.ward-pierce'),
    authoring: authoring('aetherist', 'master-plan-concept'),
  },
  {
    id: 'aetherist.arcane-field',
    contentVersion: 1,
    enabled: true,
    nameRef: 'skill.aetherist.arcane-field.name',
    descriptionRef: 'skill.aetherist.arcane-field.description',
    sourceDisciplineId: 'aetherist',
    unlockRequirement: { kind: 'discipline-mastery', minimumStage: 1 },
    apCost: 55,
    target: { ...mysticEnemyTarget, maximumRange: 3, shape: { kind: 'circle', radius: 1 } },
    requirements: [],
    effects: [
      { type: 'damage', recipient: 'affected-units', amount: 6 },
      { type: 'apply-status', recipient: 'affected-units', statusId: 'exposed', stacks: 1 },
    ],
    tags: [
      'discipline',
      'aetherist',
      'attack',
      'mystic',
      'ranged',
      'area',
      'expose',
      'cockpit:attack',
    ],
    cooldown: { key: 'aetherist.arcane-field', ownerTurns: 4 },
    ai: { enabled: true, baseUtility: 76, purposeTags: ['damage', 'area', 'debuff'] },
    overrides: {},
    media: media('aetherist.arcane-field'),
    authoring: authoring('aetherist', 'master-plan-concept'),
  },
  {
    id: 'aetherist.channel',
    contentVersion: 1,
    enabled: true,
    nameRef: 'skill.aetherist.channel.name',
    descriptionRef: 'skill.aetherist.channel.description',
    sourceDisciplineId: 'aetherist',
    unlockRequirement: { kind: 'discipline-mastery', minimumStage: 1 },
    apCost: 25,
    target: selfTarget,
    requirements: [],
    effects: [{ type: 'resource-change', recipient: 'actor', resource: 'mp', delta: 8 }],
    tags: ['discipline', 'aetherist', 'mystic', 'recovery', 'cockpit:recovery'],
    cooldown: { key: 'aetherist.channel', ownerTurns: 3 },
    ai: { enabled: true, baseUtility: 58, purposeTags: ['recovery', 'resource'] },
    overrides: {},
    media: media('aetherist.channel'),
    authoring: authoring('aetherist', 'master-plan-concept'),
  },
  {
    id: 'aetherist.mana-shield',
    contentVersion: 1,
    enabled: true,
    nameRef: 'skill.aetherist.mana-shield.name',
    descriptionRef: 'skill.aetherist.mana-shield.description',
    sourceDisciplineId: 'aetherist',
    unlockRequirement: { kind: 'discipline-mastery', minimumStage: 1 },
    apCost: 35,
    target: selfTarget,
    requirements: [],
    effects: [{ type: 'apply-status', recipient: 'actor', statusId: 'guarded', stacks: 1 }],
    tags: ['discipline', 'aetherist', 'mystic', 'defense', 'cockpit:defense'],
    cooldown: { key: 'aetherist.mana-shield', ownerTurns: 3 },
    ai: { enabled: true, baseUtility: 64, purposeTags: ['defense', 'survival'] },
    overrides: {},
    media: media('aetherist.mana-shield'),
    authoring: authoring('aetherist', 'class-expansion'),
  },
  {
    id: 'aetherist.chain-spark',
    contentVersion: 1,
    enabled: true,
    nameRef: 'skill.aetherist.chain-spark.name',
    descriptionRef: 'skill.aetherist.chain-spark.description',
    sourceDisciplineId: 'aetherist',
    unlockRequirement: { kind: 'discipline-mastery', minimumStage: 1 },
    apCost: 50,
    target: { ...mysticEnemyTarget, shape: { kind: 'line', length: 3 } },
    requirements: [],
    effects: [{ type: 'damage', recipient: 'affected-units', amount: 8 }],
    tags: ['discipline', 'aetherist', 'attack', 'mystic', 'ranged', 'area', 'cockpit:attack'],
    cooldown: { key: 'aetherist.chain-spark', ownerTurns: 3 },
    ai: { enabled: true, baseUtility: 72, purposeTags: ['damage', 'area'] },
    overrides: {},
    media: media('aetherist.chain-spark'),
    authoring: authoring('aetherist', 'class-expansion'),
  },
  {
    id: 'aetherist.overchannel',
    contentVersion: 1,
    enabled: true,
    nameRef: 'skill.aetherist.overchannel.name',
    descriptionRef: 'skill.aetherist.overchannel.description',
    sourceDisciplineId: 'aetherist',
    unlockRequirement: { kind: 'discipline-mastery', minimumStage: 1 },
    apCost: 65,
    target: mysticEnemyTarget,
    requirements: [],
    effects: [{ type: 'damage', recipient: 'primary-unit', amount: 16 }],
    tags: ['discipline', 'aetherist', 'attack', 'mystic', 'ranged', 'finisher', 'cockpit:attack'],
    cooldown: { key: 'aetherist.overchannel', ownerTurns: 4 },
    ai: { enabled: true, baseUtility: 80, purposeTags: ['damage', 'finisher'] },
    overrides: {},
    media: media('aetherist.overchannel'),
    authoring: authoring('aetherist', 'class-expansion'),
  },
  {
    id: 'farstrider.aimed-shot',
    contentVersion: 1,
    enabled: true,
    nameRef: 'skill.farstrider.aimed-shot.name',
    descriptionRef: 'skill.farstrider.aimed-shot.description',
    sourceDisciplineId: 'farstrider',
    unlockRequirement: { kind: 'discipline-mastery', minimumStage: 1 },
    apCost: 40,
    target: farEnemyTarget,
    requirements: [],
    effects: [{ type: 'damage', recipient: 'primary-unit', amount: 13 }],
    tags: ['discipline', 'farstrider', 'attack', 'ranged', 'precision', 'cockpit:attack'],
    cooldown: { key: 'farstrider.aimed-shot', ownerTurns: 2 },
    ai: { enabled: true, baseUtility: 73, purposeTags: ['damage', 'precision'] },
    overrides: {},
    media: media('farstrider.aimed-shot'),
    authoring: authoring('farstrider', 'master-plan-concept'),
  },
  {
    id: 'farstrider.pinning-shot',
    contentVersion: 1,
    enabled: true,
    nameRef: 'skill.farstrider.pinning-shot.name',
    descriptionRef: 'skill.farstrider.pinning-shot.description',
    sourceDisciplineId: 'farstrider',
    unlockRequirement: { kind: 'discipline-mastery', minimumStage: 1 },
    apCost: 40,
    target: farEnemyTarget,
    requirements: [],
    effects: [
      { type: 'damage', recipient: 'primary-unit', amount: 7 },
      { type: 'apply-status', recipient: 'primary-unit', statusId: 'exposed', stacks: 1 },
    ],
    tags: ['discipline', 'farstrider', 'attack', 'ranged', 'expose', 'cockpit:attack'],
    cooldown: { key: 'farstrider.pinning-shot', ownerTurns: 3 },
    ai: { enabled: true, baseUtility: 72, purposeTags: ['damage', 'debuff', 'setup'] },
    overrides: {},
    media: media('farstrider.pinning-shot'),
    authoring: authoring('farstrider', 'master-plan-concept'),
  },
  {
    id: 'farstrider.volley',
    contentVersion: 1,
    enabled: true,
    nameRef: 'skill.farstrider.volley.name',
    descriptionRef: 'skill.farstrider.volley.description',
    sourceDisciplineId: 'farstrider',
    unlockRequirement: { kind: 'discipline-mastery', minimumStage: 1 },
    apCost: 55,
    target: { ...farEnemyTarget, shape: { kind: 'circle', radius: 1 } },
    requirements: [],
    effects: [{ type: 'damage', recipient: 'affected-units', amount: 7 }],
    tags: ['discipline', 'farstrider', 'attack', 'ranged', 'area', 'cockpit:attack'],
    cooldown: { key: 'farstrider.volley', ownerTurns: 3 },
    ai: { enabled: true, baseUtility: 72, purposeTags: ['damage', 'area'] },
    overrides: {},
    media: media('farstrider.volley'),
    authoring: authoring('farstrider', 'master-plan-concept'),
  },
  {
    id: 'farstrider.scouts-mark',
    contentVersion: 1,
    enabled: true,
    nameRef: 'skill.farstrider.scouts-mark.name',
    descriptionRef: 'skill.farstrider.scouts-mark.description',
    sourceDisciplineId: 'farstrider',
    unlockRequirement: { kind: 'discipline-mastery', minimumStage: 1 },
    apCost: 30,
    target: { ...farEnemyTarget, minimumRange: 1 },
    requirements: [],
    effects: [{ type: 'apply-status', recipient: 'primary-unit', statusId: 'exposed', stacks: 1 }],
    tags: ['discipline', 'farstrider', 'ranged', 'mark', 'expose', 'cockpit:attack'],
    cooldown: { key: 'farstrider.scouts-mark', ownerTurns: 3 },
    ai: { enabled: true, baseUtility: 64, purposeTags: ['mark', 'debuff', 'setup'] },
    overrides: {},
    media: media('farstrider.scouts-mark'),
    authoring: authoring('farstrider', 'master-plan-concept'),
  },
  {
    id: 'farstrider.longshot',
    contentVersion: 1,
    enabled: true,
    nameRef: 'skill.farstrider.longshot.name',
    descriptionRef: 'skill.farstrider.longshot.description',
    sourceDisciplineId: 'farstrider',
    unlockRequirement: { kind: 'discipline-mastery', minimumStage: 1 },
    apCost: 55,
    target: { ...farEnemyTarget, minimumRange: 3, maximumRange: 6 },
    requirements: [],
    effects: [{ type: 'damage', recipient: 'primary-unit', amount: 17 }],
    tags: [
      'discipline',
      'farstrider',
      'attack',
      'ranged',
      'precision',
      'finisher',
      'cockpit:attack',
    ],
    cooldown: { key: 'farstrider.longshot', ownerTurns: 4 },
    ai: { enabled: true, baseUtility: 81, purposeTags: ['damage', 'precision', 'finisher'] },
    overrides: {},
    media: media('farstrider.longshot'),
    authoring: authoring('farstrider', 'class-expansion'),
  },
  {
    id: 'farstrider.piercing-barrage',
    contentVersion: 1,
    enabled: true,
    nameRef: 'skill.farstrider.piercing-barrage.name',
    descriptionRef: 'skill.farstrider.piercing-barrage.description',
    sourceDisciplineId: 'farstrider',
    unlockRequirement: { kind: 'discipline-mastery', minimumStage: 1 },
    apCost: 55,
    target: { ...farEnemyTarget, shape: { kind: 'line', length: 4 } },
    requirements: [],
    effects: [{ type: 'damage', recipient: 'affected-units', amount: 9 }],
    tags: ['discipline', 'farstrider', 'attack', 'ranged', 'area', 'cockpit:attack'],
    cooldown: { key: 'farstrider.piercing-barrage', ownerTurns: 4 },
    ai: { enabled: true, baseUtility: 76, purposeTags: ['damage', 'area', 'pressure'] },
    overrides: {},
    media: media('farstrider.piercing-barrage'),
    authoring: authoring('farstrider', 'class-expansion'),
  },
  {
    id: 'farstrider.fieldcraft',
    contentVersion: 1,
    enabled: true,
    nameRef: 'skill.farstrider.fieldcraft.name',
    descriptionRef: 'skill.farstrider.fieldcraft.description',
    sourceDisciplineId: 'farstrider',
    unlockRequirement: { kind: 'discipline-mastery', minimumStage: 1 },
    apCost: 30,
    target: selfTarget,
    requirements: [],
    effects: [
      { type: 'healing', recipient: 'actor', amount: 6 },
      { type: 'resource-change', recipient: 'actor', resource: 'mp', delta: 4 },
    ],
    tags: ['discipline', 'farstrider', 'recovery', 'survival', 'cockpit:recovery'],
    cooldown: { key: 'farstrider.fieldcraft', ownerTurns: 3 },
    ai: { enabled: true, baseUtility: 61, purposeTags: ['recovery', 'survival'] },
    overrides: {},
    media: media('farstrider.fieldcraft'),
    authoring: authoring('farstrider', 'class-expansion'),
  },
  {
    id: 'farstrider.keen-focus',
    contentVersion: 1,
    enabled: true,
    nameRef: 'skill.farstrider.keen-focus.name',
    descriptionRef: 'skill.farstrider.keen-focus.description',
    sourceDisciplineId: 'farstrider',
    unlockRequirement: { kind: 'discipline-mastery', minimumStage: 1 },
    apCost: 35,
    target: selfTarget,
    requirements: [],
    effects: [{ type: 'apply-status', recipient: 'actor', statusId: 'guarded', stacks: 1 }],
    tags: ['discipline', 'farstrider', 'defense', 'awareness', 'cockpit:defense'],
    cooldown: { key: 'farstrider.keen-focus', ownerTurns: 3 },
    ai: { enabled: true, baseUtility: 63, purposeTags: ['defense', 'awareness'] },
    overrides: {},
    media: media('farstrider.keen-focus'),
    authoring: authoring('farstrider', 'class-expansion'),
  },
  {
    id: 'shadehand.backstab',
    contentVersion: 1,
    enabled: true,
    nameRef: 'skill.shadehand.backstab.name',
    descriptionRef: 'skill.shadehand.backstab.description',
    sourceDisciplineId: 'shadehand',
    unlockRequirement: { kind: 'discipline-mastery', minimumStage: 1 },
    apCost: 40,
    target: meleeEnemyTarget,
    requirements: [],
    effects: [
      {
        type: 'damage',
        recipient: 'primary-unit',
        amount: 10,
        facingModifiersBasisPoints: { front: 10_000, side: 13_000, rear: 17_000 },
      },
    ],
    tags: ['discipline', 'shadehand', 'attack', 'melee', 'opportunist', 'cockpit:attack'],
    cooldown: { key: 'shadehand.backstab', ownerTurns: 2 },
    ai: { enabled: true, baseUtility: 76, purposeTags: ['damage', 'flank', 'rear'] },
    overrides: {},
    media: media('shadehand.backstab'),
    authoring: authoring('shadehand', 'master-plan-concept'),
  },
  {
    id: 'shadehand.feint',
    contentVersion: 1,
    enabled: true,
    nameRef: 'skill.shadehand.feint.name',
    descriptionRef: 'skill.shadehand.feint.description',
    sourceDisciplineId: 'shadehand',
    unlockRequirement: { kind: 'discipline-mastery', minimumStage: 1 },
    apCost: 35,
    target: meleeEnemyTarget,
    requirements: [],
    effects: [
      { type: 'damage', recipient: 'primary-unit', amount: 5 },
      { type: 'apply-status', recipient: 'primary-unit', statusId: 'exposed', stacks: 1 },
    ],
    tags: ['discipline', 'shadehand', 'attack', 'melee', 'expose', 'cockpit:attack'],
    cooldown: { key: 'shadehand.feint', ownerTurns: 2 },
    ai: { enabled: true, baseUtility: 69, purposeTags: ['damage', 'debuff', 'setup'] },
    overrides: {},
    media: media('shadehand.feint'),
    authoring: authoring('shadehand', 'master-plan-concept'),
  },
  {
    id: 'shadehand.smoke-vial',
    contentVersion: 1,
    enabled: true,
    nameRef: 'skill.shadehand.smoke-vial.name',
    descriptionRef: 'skill.shadehand.smoke-vial.description',
    sourceDisciplineId: 'shadehand',
    unlockRequirement: { kind: 'discipline-mastery', minimumStage: 1 },
    apCost: 35,
    target: selfTarget,
    requirements: [],
    effects: [{ type: 'apply-status', recipient: 'actor', statusId: 'guarded', stacks: 1 }],
    tags: ['discipline', 'shadehand', 'defense', 'utility', 'cockpit:defense'],
    cooldown: { key: 'shadehand.smoke-vial', ownerTurns: 3 },
    ai: { enabled: true, baseUtility: 64, purposeTags: ['defense', 'survival'] },
    overrides: {},
    media: media('shadehand.smoke-vial'),
    authoring: authoring('shadehand', 'master-plan-concept'),
  },
  {
    id: 'shadehand.crippling-cut',
    contentVersion: 1,
    enabled: true,
    nameRef: 'skill.shadehand.crippling-cut.name',
    descriptionRef: 'skill.shadehand.crippling-cut.description',
    sourceDisciplineId: 'shadehand',
    unlockRequirement: { kind: 'discipline-mastery', minimumStage: 1 },
    apCost: 45,
    target: meleeEnemyTarget,
    requirements: [],
    effects: [
      { type: 'damage', recipient: 'primary-unit', amount: 8 },
      { type: 'apply-status', recipient: 'primary-unit', statusId: 'exposed', stacks: 1 },
    ],
    tags: ['discipline', 'shadehand', 'attack', 'melee', 'expose', 'cockpit:attack'],
    cooldown: { key: 'shadehand.crippling-cut', ownerTurns: 3 },
    ai: { enabled: true, baseUtility: 72, purposeTags: ['damage', 'debuff', 'setup'] },
    overrides: {},
    media: media('shadehand.crippling-cut'),
    authoring: authoring('shadehand', 'master-plan-concept'),
  },
  {
    id: 'shadehand.exploit-opening',
    contentVersion: 1,
    enabled: true,
    nameRef: 'skill.shadehand.exploit-opening.name',
    descriptionRef: 'skill.shadehand.exploit-opening.description',
    sourceDisciplineId: 'shadehand',
    unlockRequirement: { kind: 'discipline-mastery', minimumStage: 1 },
    apCost: 45,
    target: meleeEnemyTarget,
    requirements: [{ kind: 'target-status-present', statusId: 'exposed' }],
    effects: [
      {
        type: 'damage',
        recipient: 'primary-unit',
        amount: 14,
        facingModifiersBasisPoints: { front: 10_000, side: 13_000, rear: 16_000 },
      },
    ],
    tags: [
      'discipline',
      'shadehand',
      'attack',
      'melee',
      'opportunist',
      'finisher',
      'cockpit:attack',
    ],
    cooldown: { key: 'shadehand.exploit-opening', ownerTurns: 3 },
    ai: { enabled: true, baseUtility: 82, purposeTags: ['damage', 'opportunist', 'finisher'] },
    overrides: {},
    media: media('shadehand.exploit-opening'),
    authoring: authoring('shadehand', 'class-expansion'),
  },
  {
    id: 'shadehand.fan-of-knives',
    contentVersion: 1,
    enabled: true,
    nameRef: 'skill.shadehand.fan-of-knives.name',
    descriptionRef: 'skill.shadehand.fan-of-knives.description',
    sourceDisciplineId: 'shadehand',
    unlockRequirement: { kind: 'discipline-mastery', minimumStage: 1 },
    apCost: 50,
    target: { ...meleeEnemyTarget, shape: { kind: 'circle', radius: 1 } },
    requirements: [],
    effects: [{ type: 'damage', recipient: 'affected-units', amount: 7 }],
    tags: ['discipline', 'shadehand', 'attack', 'melee', 'area', 'cockpit:attack'],
    cooldown: { key: 'shadehand.fan-of-knives', ownerTurns: 3 },
    ai: { enabled: true, baseUtility: 72, purposeTags: ['damage', 'area'] },
    overrides: {},
    media: media('shadehand.fan-of-knives'),
    authoring: authoring('shadehand', 'class-expansion'),
  },
  {
    id: 'shadehand.quick-hands',
    contentVersion: 1,
    enabled: true,
    nameRef: 'skill.shadehand.quick-hands.name',
    descriptionRef: 'skill.shadehand.quick-hands.description',
    sourceDisciplineId: 'shadehand',
    unlockRequirement: { kind: 'discipline-mastery', minimumStage: 1 },
    apCost: 25,
    target: selfTarget,
    requirements: [],
    effects: [{ type: 'resource-change', recipient: 'actor', resource: 'mp', delta: 6 }],
    tags: ['discipline', 'shadehand', 'utility', 'recovery', 'cockpit:recovery'],
    cooldown: { key: 'shadehand.quick-hands', ownerTurns: 3 },
    ai: { enabled: true, baseUtility: 57, purposeTags: ['recovery', 'resource'] },
    overrides: {},
    media: media('shadehand.quick-hands'),
    authoring: authoring('shadehand', 'class-expansion'),
  },
  {
    id: 'shadehand.execution-cut',
    contentVersion: 1,
    enabled: true,
    nameRef: 'skill.shadehand.execution-cut.name',
    descriptionRef: 'skill.shadehand.execution-cut.description',
    sourceDisciplineId: 'shadehand',
    unlockRequirement: { kind: 'discipline-mastery', minimumStage: 1 },
    apCost: 60,
    target: meleeEnemyTarget,
    requirements: [],
    effects: [
      {
        type: 'damage',
        recipient: 'primary-unit',
        amount: 16,
        facingModifiersBasisPoints: { front: 10_000, side: 14_000, rear: 18_000 },
      },
    ],
    tags: [
      'discipline',
      'shadehand',
      'attack',
      'melee',
      'opportunist',
      'finisher',
      'cockpit:attack',
    ],
    cooldown: { key: 'shadehand.execution-cut', ownerTurns: 4 },
    ai: { enabled: true, baseUtility: 84, purposeTags: ['damage', 'flank', 'finisher'] },
    overrides: {},
    media: media('shadehand.execution-cut'),
    authoring: authoring('shadehand', 'class-expansion'),
  },
] as const
