begin;

-- Private, server-owned PvP communication and spectator state.
-- Persistent spectating state is intentionally separate from expiring viewer presence.

create table if not exists app_private.pvp_active_spectating (
  user_id uuid primary key references auth.users(id) on delete cascade,
  battle_session_id uuid not null references app_private.battle_sessions(id) on delete cascade,
  started_at timestamptz not null default clock_timestamp(),
  updated_at timestamptz not null default clock_timestamp()
);

create index if not exists pvp_active_spectating_battle_idx
  on app_private.pvp_active_spectating (battle_session_id);

alter table app_private.pvp_active_spectating enable row level security;

create table if not exists app_private.pvp_battle_spectator_presence (
  battle_session_id uuid not null references app_private.battle_sessions(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  joined_at timestamptz not null default clock_timestamp(),
  last_seen_at timestamptz not null default clock_timestamp(),
  primary key (battle_session_id, user_id)
);

create index if not exists pvp_battle_spectator_presence_last_seen_idx
  on app_private.pvp_battle_spectator_presence (battle_session_id, last_seen_at desc);

alter table app_private.pvp_battle_spectator_presence enable row level security;

create table if not exists app_private.pvp_battle_chat_messages (
  id bigint generated by default as identity primary key,
  battle_session_id uuid not null references app_private.battle_sessions(id) on delete cascade,
  sender_user_id uuid not null references auth.users(id) on delete cascade,
  sender_character_id uuid not null references public.characters(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 280),
  created_at timestamptz not null default clock_timestamp()
);

create index if not exists pvp_battle_chat_messages_battle_id_idx
  on app_private.pvp_battle_chat_messages (battle_session_id, id);

alter table app_private.pvp_battle_chat_messages enable row level security;

create or replace function public.join_pvp_spectator_v1(
  p_user_id uuid,
  p_battle_key text
)
returns table (battle_session_id uuid)
language plpgsql
security definer
set search_path = pg_catalog, public, app_private
as $$
declare
  v_battle_session_id uuid;
  v_existing uuid;
begin
  select l.battle_session_id
    into v_battle_session_id
  from app_private.pvp_lobbies l
  join app_private.battle_sessions b on b.id = l.battle_session_id
  where l.battle_key = p_battle_key
    and l.battle_session_id is not null
    and l.status in ('active', 'completed')
    and b.lifecycle in ('active', 'completed')
  limit 1;

  if v_battle_session_id is null then
    return;
  end if;

  if exists (
    select 1
    from app_private.battle_participants bp
    join app_private.battle_sessions b on b.id = bp.battle_session_id
    where bp.user_id = p_user_id
      and b.lifecycle = 'active'
  ) then
    raise exception 'PVP_SPECTATE_CONFLICT' using errcode = '42501';
  end if;

  select s.battle_session_id into v_existing
  from app_private.pvp_active_spectating s
  where s.user_id = p_user_id;

  if v_existing is not null and v_existing <> v_battle_session_id then
    raise exception 'PVP_SPECTATE_CONFLICT' using errcode = '42501';
  end if;

  insert into app_private.pvp_active_spectating (
    user_id,
    battle_session_id,
    started_at,
    updated_at
  ) values (
    p_user_id,
    v_battle_session_id,
    clock_timestamp(),
    clock_timestamp()
  )
  on conflict (user_id) do update set
    battle_session_id = excluded.battle_session_id,
    updated_at = excluded.updated_at;

  insert into app_private.pvp_battle_spectator_presence (
    battle_session_id,
    user_id,
    joined_at,
    last_seen_at
  ) values (
    v_battle_session_id,
    p_user_id,
    clock_timestamp(),
    clock_timestamp()
  )
  on conflict (battle_session_id, user_id) do update set
    last_seen_at = excluded.last_seen_at;

  return query select v_battle_session_id;
end;
$$;

create or replace function public.heartbeat_pvp_spectator_v1(
  p_user_id uuid,
  p_battle_session_id uuid
)
returns boolean
language plpgsql
security definer
set search_path = pg_catalog, public, app_private
as $$
begin
  if not exists (
    select 1
    from app_private.pvp_active_spectating s
    where s.user_id = p_user_id
      and s.battle_session_id = p_battle_session_id
  ) then
    return false;
  end if;

  insert into app_private.pvp_battle_spectator_presence (
    battle_session_id,
    user_id,
    joined_at,
    last_seen_at
  ) values (
    p_battle_session_id,
    p_user_id,
    clock_timestamp(),
    clock_timestamp()
  )
  on conflict (battle_session_id, user_id) do update set
    last_seen_at = excluded.last_seen_at;

  return true;
end;
$$;

create or replace function public.leave_pvp_spectator_v1(
  p_user_id uuid,
  p_battle_session_id uuid
)
returns boolean
language plpgsql
security definer
set search_path = pg_catalog, public, app_private
as $$
declare
  v_removed integer := 0;
begin
  delete from app_private.pvp_battle_spectator_presence
  where battle_session_id = p_battle_session_id
    and user_id = p_user_id;

  delete from app_private.pvp_active_spectating
  where user_id = p_user_id
    and battle_session_id = p_battle_session_id;
  get diagnostics v_removed = row_count;

  return v_removed > 0;
end;
$$;

create or replace function public.get_active_spectating_for_user_v1(
  p_user_id uuid
)
returns table (
  battle_session_id uuid,
  battle_key text,
  updated_at timestamptz
)
language sql
security definer
set search_path = pg_catalog, public, app_private
as $$
  select s.battle_session_id, l.battle_key, s.updated_at
  from app_private.pvp_active_spectating s
  join app_private.battle_sessions b on b.id = s.battle_session_id
  join app_private.pvp_lobbies l on l.battle_session_id = s.battle_session_id
  where s.user_id = p_user_id
    and b.lifecycle in ('active', 'completed')
  limit 1;
$$;

create or replace function public.get_pvp_spectator_count_v1(
  p_user_id uuid,
  p_battle_session_id uuid
)
returns integer
language plpgsql
security definer
set search_path = pg_catalog, public, app_private
as $$
declare
  v_authorized boolean;
  v_count integer;
begin
  delete from app_private.pvp_battle_spectator_presence
  where last_seen_at < clock_timestamp() - interval '45 seconds';

  select (
    exists (
      select 1 from app_private.battle_participants bp
      where bp.battle_session_id = p_battle_session_id and bp.user_id = p_user_id
    )
    or exists (
      select 1 from app_private.pvp_active_spectating s
      where s.battle_session_id = p_battle_session_id and s.user_id = p_user_id
    )
  ) into v_authorized;

  if not v_authorized then
    raise exception 'PVP_BATTLE_FORBIDDEN' using errcode = '42501';
  end if;

  select count(*)::integer into v_count
  from app_private.pvp_battle_spectator_presence s
  where s.battle_session_id = p_battle_session_id
    and s.last_seen_at >= clock_timestamp() - interval '45 seconds';

  return v_count;
end;
$$;

create or replace function public.list_pvp_spectators_v1(
  p_user_id uuid,
  p_battle_session_id uuid
)
returns table (
  spectator_name text,
  last_seen_at timestamptz
)
language plpgsql
security definer
set search_path = pg_catalog, public, app_private
as $$
declare
  v_authorized boolean;
begin
  delete from app_private.pvp_battle_spectator_presence
  where last_seen_at < clock_timestamp() - interval '45 seconds';

  select (
    exists (
      select 1 from app_private.battle_participants bp
      where bp.battle_session_id = p_battle_session_id and bp.user_id = p_user_id
    )
    or exists (
      select 1 from app_private.pvp_active_spectating s
      where s.battle_session_id = p_battle_session_id and s.user_id = p_user_id
    )
  ) into v_authorized;

  if not v_authorized then
    raise exception 'PVP_BATTLE_FORBIDDEN' using errcode = '42501';
  end if;

  return query
  select
    coalesce(character_name.name, 'Spectator') as spectator_name,
    presence.last_seen_at
  from app_private.pvp_battle_spectator_presence presence
  left join lateral (
    select c.name
    from public.characters c
    where c.user_id = presence.user_id
    order by c.last_active_at desc nulls last, c.created_at desc
    limit 1
  ) character_name on true
  where presence.battle_session_id = p_battle_session_id
    and presence.last_seen_at >= clock_timestamp() - interval '45 seconds'
  order by presence.joined_at asc;
end;
$$;

create or replace function public.list_pvp_battle_chat_v1(
  p_user_id uuid,
  p_battle_session_id uuid,
  p_after_id bigint default 0
)
returns table (
  message_id bigint,
  sender_character_id uuid,
  sender_character_name text,
  body text,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = pg_catalog, public, app_private
as $$
declare
  v_authorized boolean;
begin
  select (
    exists (
      select 1 from app_private.battle_participants bp
      where bp.battle_session_id = p_battle_session_id and bp.user_id = p_user_id
    )
    or exists (
      select 1 from app_private.pvp_active_spectating s
      where s.battle_session_id = p_battle_session_id and s.user_id = p_user_id
    )
  ) into v_authorized;

  if not v_authorized then
    raise exception 'PVP_BATTLE_FORBIDDEN' using errcode = '42501';
  end if;

  return query
  select m.id, m.sender_character_id, c.name, m.body, m.created_at
  from app_private.pvp_battle_chat_messages m
  join public.characters c on c.id = m.sender_character_id
  where m.battle_session_id = p_battle_session_id
    and m.id > greatest(coalesce(p_after_id, 0), 0)
  order by m.id asc
  limit 100;
end;
$$;

create or replace function public.send_pvp_battle_chat_v1(
  p_user_id uuid,
  p_battle_session_id uuid,
  p_body text
)
returns table (
  message_id bigint,
  sender_character_id uuid,
  sender_character_name text,
  body text,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = pg_catalog, public, app_private
as $$
declare
  v_character_id uuid;
  v_body text;
  v_message_id bigint;
begin
  v_body := btrim(coalesce(p_body, ''));
  if char_length(v_body) < 1 or char_length(v_body) > 280 then
    raise exception 'PVP_CHAT_INVALID' using errcode = '22023';
  end if;

  select bp.character_id
    into v_character_id
  from app_private.battle_participants bp
  join app_private.battle_sessions b on b.id = bp.battle_session_id
  where bp.battle_session_id = p_battle_session_id
    and bp.user_id = p_user_id
    and bp.character_id is not null
    and b.lifecycle = 'active'
  limit 1;

  if v_character_id is null then
    raise exception 'PVP_CHAT_FORBIDDEN' using errcode = '42501';
  end if;

  insert into app_private.pvp_battle_chat_messages (
    battle_session_id,
    sender_user_id,
    sender_character_id,
    body
  ) values (
    p_battle_session_id,
    p_user_id,
    v_character_id,
    v_body
  ) returning id into v_message_id;

  return query
  select m.id, m.sender_character_id, c.name, m.body, m.created_at
  from app_private.pvp_battle_chat_messages m
  join public.characters c on c.id = m.sender_character_id
  where m.id = v_message_id;
end;
$$;

create or replace function public.list_pvp_battle_events_v1(
  p_user_id uuid,
  p_battle_session_id uuid,
  p_limit integer default 100
)
returns table (
  battle_version bigint,
  event_index integer,
  event jsonb,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = pg_catalog, public, app_private
as $$
declare
  v_authorized boolean;
  v_limit integer := greatest(1, least(coalesce(p_limit, 100), 100));
begin
  select (
    exists (
      select 1 from app_private.battle_participants bp
      where bp.battle_session_id = p_battle_session_id and bp.user_id = p_user_id
    )
    or exists (
      select 1 from app_private.pvp_active_spectating s
      where s.battle_session_id = p_battle_session_id and s.user_id = p_user_id
    )
  ) into v_authorized;

  if not v_authorized then
    raise exception 'PVP_BATTLE_FORBIDDEN' using errcode = '42501';
  end if;

  return query
  select recent.battle_version, recent.event_index, recent.event, recent.created_at
  from (
    select e.battle_version, e.event_index, e.event, e.created_at
    from app_private.battle_events e
    where e.battle_session_id = p_battle_session_id
    order by e.battle_version desc, e.event_index desc
    limit v_limit
  ) recent
  order by recent.battle_version asc, recent.event_index asc;
end;
$$;

revoke all on table app_private.pvp_active_spectating from public, anon, authenticated;
revoke all on table app_private.pvp_battle_spectator_presence from public, anon, authenticated;
revoke all on table app_private.pvp_battle_chat_messages from public, anon, authenticated;

revoke all on function public.join_pvp_spectator_v1(uuid, text) from public, anon, authenticated;
revoke all on function public.heartbeat_pvp_spectator_v1(uuid, uuid) from public, anon, authenticated;
revoke all on function public.leave_pvp_spectator_v1(uuid, uuid) from public, anon, authenticated;
revoke all on function public.get_active_spectating_for_user_v1(uuid) from public, anon, authenticated;
revoke all on function public.get_pvp_spectator_count_v1(uuid, uuid) from public, anon, authenticated;
revoke all on function public.list_pvp_spectators_v1(uuid, uuid) from public, anon, authenticated;
revoke all on function public.list_pvp_battle_chat_v1(uuid, uuid, bigint) from public, anon, authenticated;
revoke all on function public.send_pvp_battle_chat_v1(uuid, uuid, text) from public, anon, authenticated;
revoke all on function public.list_pvp_battle_events_v1(uuid, uuid, integer) from public, anon, authenticated;

grant execute on function public.join_pvp_spectator_v1(uuid, text) to service_role;
grant execute on function public.heartbeat_pvp_spectator_v1(uuid, uuid) to service_role;
grant execute on function public.leave_pvp_spectator_v1(uuid, uuid) to service_role;
grant execute on function public.get_active_spectating_for_user_v1(uuid) to service_role;
grant execute on function public.get_pvp_spectator_count_v1(uuid, uuid) to service_role;
grant execute on function public.list_pvp_spectators_v1(uuid, uuid) to service_role;
grant execute on function public.list_pvp_battle_chat_v1(uuid, uuid, bigint) to service_role;
grant execute on function public.send_pvp_battle_chat_v1(uuid, uuid, text) to service_role;
grant execute on function public.list_pvp_battle_events_v1(uuid, uuid, integer) to service_role;

commit;
