/** Original generated battle material candidates for the Owner-authorized review build.
 * Source masters, prompts and deterministic derivative provenance: ART-BATTLE-007. */
export const BATTLE_ART = [
  {
    id: 'ui.battle.cockpit-ornament.v01',
    kind: 'ui',
    status: 'approved',
    requestId: 'ART-BATTLE-COCKPIT-20261002',
    generationRequestId: 'exec-d9e8652b-aa7a-43d9-b6d0-752f9d10aa61',
    decorative: true,
    alt: '',
    src: '/media/art/battle/cockpit-ornament-v01.webp',
    width: 2172,
    height: 724,
  },
  {
    id: 'environment.battle.citadel-dusk.v01',
    kind: 'environment',
    status: 'approved',
    requestId: 'ART-BATTLE-007',
    generationRequestId: '222bcc29-1e83-440d-92f6-1c82b3d0f3dd',
    decorative: true,
    alt: '',
    src: '/media/art/battle/citadel-dusk-v01.webp',
    width: 1672,
    height: 941,
  },
  {
    id: 'environment.battle.enchanted-arena.v01',
    kind: 'environment',
    status: 'approved',
    requestId: 'ART-BATTLE-007',
    generationRequestId: '9d91ffdd-90f9-4e94-9c23-ec5c763033ba',
    decorative: true,
    alt: '',
    src: '/media/art/battle/enchanted-arena-v01.webp',
    width: 1672,
    height: 941,
  },
  {
    id: 'terrain.battle.open-stone.v01',
    kind: 'environment',
    status: 'approved',
    requestId: 'ART-BATTLE-007',
    generationRequestId: '8f85635a-207e-478b-9605-b63544982c73',
    decorative: true,
    alt: '',
    src: '/media/art/battle/terrain-open-stone-v01.webp',
    width: 384,
    height: 384,
  },
  {
    id: 'terrain.battle.rough-moss.v01',
    kind: 'environment',
    status: 'approved',
    requestId: 'ART-BATTLE-007',
    generationRequestId: '54b89307-6864-4f0a-8be7-0aff51707df2',
    decorative: true,
    alt: '',
    src: '/media/art/battle/terrain-rough-moss-v01.webp',
    width: 384,
    height: 384,
  },
  {
    id: 'terrain.battle.raised-ledge.v02',
    kind: 'environment',
    status: 'approved',
    requestId: 'ART-BATTLE-029',
    decorative: true,
    alt: '',
    src: '/media/art/battle/terrain-raised-ledge-v02.webp',
    width: 512,
    height: 512,
  },
] as const
