/** Original generated battle material candidates for the Owner-authorized review build.
 * Source masters, prompts and deterministic derivative provenance: ART-BATTLE-007. */
export const BATTLE_ART = [
  {
    id: 'environment.battle.citadel-dusk.v01',
    kind: 'environment',
    status: 'approved',
    requestId: 'ART-BATTLE-007',
    generationRequestId: '222bcc29-1e83-440d-92f6-1c82b3d0f3dd',
    decorative: true,
    alt: '',
    src: '/media/art/battle/citadel-dusk-v01.webp',
    width: 1672,
    height: 941,
  },
  {
    id: 'environment.battle.enchanted-arena.v01',
    kind: 'environment',
    status: 'approved',
    requestId: 'ART-BATTLE-007',
    generationRequestId: '9d91ffdd-90f9-4e94-9c23-ec5c763033ba',
    decorative: true,
    alt: '',
    src: '/media/art/battle/enchanted-arena-v01.webp',
    width: 1672,
    height: 941,
  },
  {
    id: 'terrain.battle.open-stone.v01',
    kind: 'environment',
    status: 'approved',
    requestId: 'ART-BATTLE-007',
    generationRequestId: '8f85635a-207e-478b-9605-b63544982c73',
    decorative: true,
    alt: '',
    src: '/media/art/battle/terrain-open-stone-v01.webp',
    width: 384,
    height: 384,
  },
  {
    id: 'terrain.battle.rough-moss.v01',
    kind: 'environment',
    status: 'approved',
    requestId: 'ART-BATTLE-007',
    generationRequestId: '54b89307-6864-4f0a-8be7-0aff51707df2',
    decorative: true,
    alt: '',
    src: '/media/art/battle/terrain-rough-moss-v01.webp',
    width: 384,
    height: 384,
  },
  {
    id: 'terrain.battle.raised-stone.v01',
    kind: 'environment',
    status: 'approved',
    requestId: 'ART-BATTLE-007',
    generationRequestId: 'bb38aecc-0f05-412f-9fe5-6bceacf64b26',
    decorative: true,
    alt: '',
    src: '/media/art/battle/terrain-raised-stone-v01.webp',
    width: 384,
    height: 384,
  },
] as const
